ScrollLayoutApp:


<ScrollLayoutApp>:
    orientation: "horizontal"
    GridLayoutA:
        height: self.minimum_height


<GridLayoutA>:
    rows: 4
    columns: 2
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
    Button:
        text: "A"
